// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB48BAaWk7K1ymW0bcPun5aKLGZTZvgzMA',
    appId: '1:755730133759:web:1d812dd55aa37606c092ca',
    messagingSenderId: '755730133759',
    projectId: 'grewox-infotech-nesticop-14b19',
    authDomain: 'grewox-infotech-nesticop-14b19.firebaseapp.com',
    storageBucket: 'grewox-infotech-nesticop-14b19.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbJmA6vgDI1V6xznO6uBroFZoL1jGvf4k',
    appId: '1:755730133759:android:8d62b8a0dc0905efc092ca',
    messagingSenderId: '755730133759',
    projectId: 'grewox-infotech-nesticop-14b19',
    storageBucket: 'grewox-infotech-nesticop-14b19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP-Q8aO2cXPHpcLkLTXCEA48yut6A9PoI',
    appId: '1:755730133759:ios:53e33b859af78115c092ca',
    messagingSenderId: '755730133759',
    projectId: 'grewox-infotech-nesticop-14b19',
    storageBucket: 'grewox-infotech-nesticop-14b19.firebasestorage.app',
    iosBundleId: 'com.nesticope.app',
  );
}
