import '../data/network/property/models/property_model.dart';
import '../modules/reseller/model/reseller_lead_model/reseller_lead_overview.dart';



final List<Map<String, String>> services = [
  {
    "name": "Planning & Design",
    "lottieUrl": "https://lottie.host/c184a6a1-69a2-4856-b454-e1667ed30e21/EyPqNZs6lB.lottie"
  },
  {
    "name": "Approvals & Legal Work",
    "lottieUrl": "https://lottie.host/a1c5b421-20b1-4ad6-b546-4c213c8cd62d/LNP0QHVUMx.lottie"
  },
  {
    "name": "Construction Execution",
    "lottieUrl": "https://lottie.host/9c5fc812-2a64-49a5-b2bf-6704920a6038/gzNeh6S7PY.lottie"
  },
  {
    "name": "Material Supply",
    "lottieUrl": "https://lottie.host/6cdf8b3c-76b0-46fc-ba94-395ebfc3b429/1DAVShHNZY.lottie"
  },
  {
    "name": "Renovation & Remodeling",
    "lottieUrl": "https://lottie.host/22ff1561-e3ca-4868-8b1d-08ba8023d549/VY4Zk2T7Ay.lottie"
  },
  {
    "name": "Interior Work",
    "lottieUrl": "https://lottie.host/7e77e871-6f69-4e87-9c10-06e95445ff54/BIaMFCeAVR.lottie"
  },
  {
    "name": "MEP Services",
    "lottieUrl": "https://lottie.host/1261f3c3-0fdf-4e21-9f13-08f5ce7d0721/6whVJfyBbv.lottie"
  },
  {
    "name": "Smart Building Solutions",
    "lottieUrl": "https://lottie.host/d03eb4ec-d3cf-47a5-992d-59fa793639a7/osruVx2ggI.lottie"
  },
  {
    "name": "Maintenance & AMC",
    "lottieUrl": "https://lottie.host/0585468f-fa70-49d2-8155-3e584ebb3ff5/QTf6e73pYD.lottie"
  },
  {
    "name": "Specialized Services",
    "lottieUrl": "https://lottie.host/9cf23a6b-4443-4cf4-aaed-9007cf5aa3ea/zvH2i9jr5N.lottie"
  },
];





List<Map<String, dynamic>> propertyList = [
  {
    "id": 1,
    "title": "Luxury Apartment in City Center",
    "type": "Apartment",
    "price": 8500000.00,
    "percentage_increase": "13.4",
    "price_per_sqft": (8500000 / 1450).toStringAsFixed(2),
    "area_sqft": 1450,
    "builder": "ABC Builders",
    "establish_year": 1995,
    "projects_count": 12,
    "logo": "assets/logo/Avant.jpg",
    "price_range": {"min": "80 Lakh", "max": "90 Lakh"},
    "currency": "INR",
    "status": "For Sale",
    "bedrooms": 3,
    "bathrooms": 2,
    "address": {
      "street": "MG Road",
      "city": "Mumbai",
      "state": "Maharashtra",
      "pincode": "400001",
    },

    "good_things": [
      "Clean and well-maintained property",
      "Safe and secure location",
      "Friendly and responsive owner/agent",
      "Easy and smooth booking process",
      "Affordable pricing compared to market",
      "Modern amenities (Wi-Fi, parking, appliances, etc.)",
      "Comfortable interiors and good furniture",

      "Accurate property photos and descriptions",
      "Quick issue resolution / good customer support",
    ],
    "needs_improvement": [
      "Property not clean or poorly maintained",
      "Noisy or unsafe neighborhood",
      "Unresponsive owner/agent",
      "Complicated booking or payment process",
      "High pricing for value offered",
      "Missing or broken amenities",

      "Inconvenient location or lack of accessibility",
      "Misleading property photos/descriptions",
      "Delayed issue resolution / poor support",
    ],

    "complete_address": "MG Road, Mumbai, Maharashtra, 400001",
    "amenities": ["Gym", "Swimming Pool", "Parking", "24x7 Security"],
    "image":
        "assets/image/modern-residential-buildings-with-wooden-facades.jpg",
    "owner": {
      "name": "Rohit Sharma",
      "contact": "+91-9876543210",
      "email": "rohit@example.com",
    },
    "seller": {
      "name": "Ravi Sharma",
      "experience": 12,
      "location": "Mumbai",
      "properties_count": 25,
      "total_active_properties": 20,
      "buy": 12,
      "rent": 5,
      "commercial_buy": 2,
      "commercial_rent": 1,
      "proprietorship": "Individual",
      "description":
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",
      "area_of_operation": ["South Mumbai", "Bandra", "Andheri"],
      "image": "assets/profile/profile.png",
    },
    "rating": 4.5,

    // ✅ New Analytics
    "appreciation_1yr": 12.8,
    "avg_rate_per_sqft": 6100,
    "transactions_1yr": 36,

    "price_trend": [
      {"year": 2020, "price": 6800000},
      {"year": 2021, "price": 7200000},
      {"year": 2022, "price": 7800000},
      {"year": 2023, "price": 8200000},
      {"year": 2024, "price": 8500000},
    ],
  },
  {
    "id": 2,
    "title": "2 BHK Flat near Railway Station",
    "type": "Flat",
    "percentage_increase": "3.9",
    "price": 22000,
    "price_per_sqft": (22000 / 950).toStringAsFixed(2),
    "area_sqft": 950,
    "price_range": {"min": "54.20 Lakh", "max": "60.1 Lakh"},
    "currency": "INR",

    "status": "For Rent",
    "builder": "ABC Builders",
    "good_things": [
      "Clean and well-maintained property",
      "Safe and secure location",
      "Friendly and responsive owner/agent",
      "Easy and smooth booking process",
      "Affordable pricing compared to market",
      "Modern amenities (Wi-Fi, parking, appliances, etc.)",
      "Comfortable interiors and good furniture",
      "Good neighborhood and accessibility (shops, transport, schools)",
      "Accurate property photos and descriptions",
      "Quick issue resolution / good customer support",
    ],
    "needs_improvement": [
      "Property not clean or poorly maintained",
      "Noisy or unsafe neighborhood",
      "Unresponsive owner/agent",
      "Complicated booking or payment process",
      "High pricing for value offered",
      "Missing or broken amenities",
      "Poor interior condition (furniture, walls, appliances)",
      "Inconvenient location or lack of accessibility",
      "Misleading property photos/descriptions",
      "Delayed issue resolution / poor support",
    ],
    "bedrooms": 2,
    "establish_year": 1995,
    "projects_count": 12,
    "logo": "assets/logo/Avant.jpg",
    "bathrooms": 1,
    "address": {
      "street": "Station Road",
      "city": "Delhi",
      "state": "Delhi",
      "pincode": "110001",
    },
    "complete_address": "Station Road, Delhi, 110001",
    "amenities": ["Lift", "Parking", "CCTV"],
    "image": "assets/image/urban-traffic-with-cityscape.jpg",
    "owner": {
      "name": "Neha Verma",
      "contact": "+91-9988776655",
      "email": "neha@example.com",
    },
    "seller": {
      "name": "Neha Kapoor",
      "experience": 8,
      "location": "Delhi",
      "properties_count": 18,
      "total_active_properties": 14,
      "buy": 7,
      "rent": 4,
      "commercial_buy": 2,
      "commercial_rent": 1,
      "proprietorship": "Individual",
      "description":
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",
      "area_of_operation": ["Connaught Place", "Gurgaon", "Noida"],
      "image": "assets/profile/profile1.png",
    },
    "rating": 4.0,

    // ✅ New Analytics
    "appreciation_1yr": 4.2,
    "avg_rate_per_sqft": 5750,
    "transactions_1yr": 22,

    "price_trend": [
      {"year": 2020, "price": 18000},
      {"year": 2021, "price": 19000},
      {"year": 2022, "price": 20000},
      {"year": 2023, "price": 21000},
      {"year": 2024, "price": 22000},
    ],
  },
  {
    "id": 3,
    "title": "Independent Villa with Garden",
    "type": "Villa",
    "price": 16500000,
    "price_per_sqft": (16500000 / 2800).toStringAsFixed(2),
    "area_sqft": 2800,
    "percentage_increase": "2.5",
    "price_range": {"min": "2.5 Cr", "max": "6.1 Cr"},
    "currency": "INR",
    "status": "For Sale",
    "builder": "ABC Builders",
    "establish_year": 1995,
    "projects_count": 12,
    "logo": "assets/logo/Avant.jpg",
    "good_things": [
      "Clean and well-maintained property",
      "Safe and secure location",
      "Friendly and responsive owner/agent",
      "Easy and smooth booking process",
      "Affordable pricing compared to market",
      "Modern amenities (Wi-Fi, parking, appliances, etc.)",
      "Comfortable interiors and good furniture",
      "Good neighborhood and accessibility (shops, transport, schools)",
      "Accurate property photos and descriptions",
      "Quick issue resolution / good customer support",
    ],
    "needs_improvement": [
      "Property not clean or poorly maintained",
      "Noisy or unsafe neighborhood",
      "Unresponsive owner/agent",
      "Complicated booking or payment process",
      "High pricing for value offered",
      "Missing or broken amenities",
      "Poor interior condition (furniture, walls, appliances)",
      "Inconvenient location or lack of accessibility",
      "Misleading property photos/descriptions",
      "Delayed issue resolution / poor support",
    ],
    "bedrooms": 4,
    "bathrooms": 3,
    "address": {
      "street": "Palm Meadows",
      "city": "Pune",
      "state": "Maharashtra",
      "pincode": "411001",
    },
    "complete_address": "Palm Meadows, Pune, Maharashtra, 411001",
    "amenities": ["Private Garden", "Car Parking", "Modular Kitchen"],
    "image": "assets/image/vertical-shot-modern-apartments-daytime.jpg",
    "owner": {
      "name": "Arjun Kapoor",
      "contact": "+91-9090909090",
      "email": "arjun@example.com",
    },
    "seller": {
      "name": "Amit Real Estates",
      "experience": 15,
      "location": "Pune",
      "properties_count": 40,
      "total_active_properties": 32,
      "buy": 20,
      "rent": 6,
      "commercial_buy": 4,
      "commercial_rent": 2,
      "proprietorship": "Company",
      "description":
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",
      "area_of_operation": ["Koregaon Park", "Hinjewadi", "Kalyani Nagar"],
      "image": "assets/profile/profile2.png",
    },
    "rating": 4.8,

    // ✅ New Analytics
    "appreciation_1yr": 6.5,
    "avg_rate_per_sqft": 5900,
    "transactions_1yr": 28,

    "price_trend": [
      {"year": 2020, "price": 14000000},
      {"year": 2021, "price": 14800000},
      {"year": 2022, "price": 15500000},
      {"year": 2023, "price": 16000000},
      {"year": 2024, "price": 16500000},
    ],
  },
  {
    "id": 4,
    "title": "Commercial Office Space",
    "type": "Office",
    "price": 75000,
    "percentage_increase": "17.13",
    "price_per_sqft": (75000 / 1200).toStringAsFixed(2),
    "area_sqft": 1200,
    "price_range": {"min": "25.20 Lakh", "max": "27.1 Lakh"},
    "currency": "INR",
    "builder": "Dream Homes Pvt Ltd",
    "establish_year": 1995,
    "projects_count": 12,
    "logo": "assets/logo/Avant.jpg",
    "good_things": [
      "Clean and well-maintained property",
      "Safe and secure location",
      "Friendly and responsive owner/agent",
      "Easy and smooth booking process",
      "Affordable pricing compared to market",
      "Modern amenities (Wi-Fi, parking, appliances, etc.)",
      "Comfortable interiors and good furniture",
      "Good neighborhood and accessibility (shops, transport, schools)",
      "Accurate property photos and descriptions",
      "Quick issue resolution / good customer support",
    ],
    "needs_improvement": [
      "Property not clean or poorly maintained",
      "Noisy or unsafe neighborhood",
      "Unresponsive owner/agent",
      "Complicated booking or payment process",
      "High pricing for value offered",
      "Missing or broken amenities",
      "Poor interior condition (furniture, walls, appliances)",
      "Inconvenient location or lack of accessibility",
      "Misleading property photos/descriptions",
      "Delayed issue resolution / poor support",
    ],
    "status": "For Rent",
    "bedrooms": 0,
    "bathrooms": 2,
    "address": {
      "street": "Cyber City",
      "city": "Bangalore",
      "state": "Karnataka",
      "pincode": "560001",
    },
    "complete_address": "Cyber City, Bangalore, Karnataka, 560001",
    "amenities": ["Power Backup", "Lift", "Conference Room"],
    "image":
        "assets/image/modern-residential-buildings-with-wooden-facades.jpg",
    "owner": {
      "name": "Shweta Singh",
      "contact": "+91-9123456789",
      "email": "shweta@example.com",
    },
    "seller": {
      "name": "Sunrise Properties",
      "experience": 10,
      "location": "Bangalore",
      "properties_count": 30,
      "total_active_properties": 24,
      "buy": 12,
      "rent": 6,
      "commercial_buy": 3,
      "commercial_rent": 3,
      "proprietorship": "Company",
      "description":
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",
      "area_of_operation": ["Whitefield", "Electronic City", "Indiranagar"],
      "image": "assets/profile/profile3.png",
    },
    "rating": 3.9,

    // ✅ New Analytics
    "appreciation_1yr": 10.2,
    "avg_rate_per_sqft": 5000,
    "transactions_1yr": 19,

    "price_trend": [
      {"year": 2020, "price": 60000},
      {"year": 2021, "price": 63000},
      {"year": 2022, "price": 67000},
      {"year": 2023, "price": 71000},
      {"year": 2024, "price": 75000},
    ],
  },
  {
    "id": 5,
    "title": "Luxury Villa on ECR Road",
    "type": "Villa",
    "price": 9800000,
    "percentage_increase": "6.13",
    "price_per_sqft": (9800000 / 1800).toStringAsFixed(2),
    "area_sqft": 1800,
    "price_range": {"min": "90 Lakh", "max": "1.1 Cr"},
    "currency": "INR",
    "builder": "Dream Homes Pvt Ltd",
    "good_things": [
      "Clean and well-maintained property",
      "Safe and secure location",
      "Friendly and responsive owner/agent",
      "Easy and smooth booking process",
      "Affordable pricing compared to market",
      "Modern amenities (Wi-Fi, parking, appliances, etc.)",
      "Comfortable interiors and good furniture",
      "Good neighborhood and accessibility (shops, transport, schools)",
      "Accurate property photos and descriptions",
      "Quick issue resolution / good customer support",
    ],
    "needs_improvement": [
      "Property not clean or poorly maintained",
      "Noisy or unsafe neighborhood",
      "Unresponsive owner/agent",
      "Complicated booking or payment process",
      "High pricing for value offered",
      "Missing or broken amenities",
      "Poor interior condition (furniture, walls, appliances)",
      "Inconvenient location or lack of accessibility",
      "Misleading property photos/descriptions",
      "Delayed issue resolution / poor support",
    ],
    "status": "For Sale",
    "establish_year": 2010,
    "projects_count": 4,
    "logo": "assets/logo/Avant.jpg",
    "bedrooms": 3,
    "bathrooms": 3,
    "address": {
      "street": "ECR Road",
      "city": "Chennai",
      "state": "Tamil Nadu",
      "pincode": "600041",
    },
    "complete_address": "ECR Road, Chennai, Tamil Nadu, 600041",
    "amenities": ["Sea View", "Car Parking", "Security"],
    "image": "assets/image/vertical-shot-modern-apartments-daytime.jpg",
    "owner": {
      "name": "Karthik Iyer",
      "contact": "+91-7777777777",
      "email": "karthik@example.com",
    },
    "seller": {
      "name": "Karan Verma",
      "experience": 6,
      "location": "Chennai",
      "properties_count": 12,
      "total_active_properties": 9,
      "buy": 4,
      "rent": 3,
      "commercial_buy": 1,
      "commercial_rent": 1,
      "proprietorship": "Individual",
      "description":
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",
      "area_of_operation": ["Anna Nagar", "T Nagar", "OMR"],
      "image": "assets/profile/profile4.png",
    },
    "rating": 4.6,

    // ✅ New Analytics
    "appreciation_1yr": 8.7,
    "avg_rate_per_sqft": 5450,
    "transactions_1yr": 25,

    "price_trend": [
      {"year": 2020, "price": 8500000},
      {"year": 2021, "price": 8800000},
      {"year": 2022, "price": 9100000},
      {"year": 2023, "price": 9500000},
      {"year": 2024, "price": 9800000},
    ],
  },
];

final Map<String, List<String>> popularCitiesWithAreas = {
  'Mumbai': [
    'Bandra',
    'Andheri',
    'Juhu',
    'Powai',
    'Borivali',
    'Colaba',
    'Andheri',
    'Juhu',
    'Powai',
    'Borivali',
    'Colaba',
  ],
  'Delhi': [
    'Connaught Place',
    'Saket',
    'Hauz Khas',
    'Karol Bagh',
    'Dwarka',
    'Vasant Kunj',
  ],
  'Bengaluru': [
    'Whitefield',
    'Indiranagar',
    'Koramangala',
    'Jayanagar',
    'MG Road',
    'Electronic City',
  ],
  'Hyderabad': [
    'Banjara Hills',
    'Jubilee Hills',
    'Gachibowli',
    'Madhapur',
    'Begumpet',
    'Hitech City',
  ],
  'Ahmedabad': [
    'Satellite',
    'Vastrapur',
    'Navrangpura',
    'Bodakdev',
    'CG Road',
    'Maninagar',
  ],
  'Chennai': [
    'T. Nagar',
    'Anna Nagar',
    'Velachery',
    'Adyar',
    'Nungambakkam',
    'Tambaram',
  ],
  'Kolkata': [
    'Salt Lake',
    'Park Street',
    'Ballygunge',
    'Howrah',
    'Dum Dum',
    'New Town',
  ],
  'Pune': [
    'Koregaon Park',
    'Viman Nagar',
    'Kothrud',
    'Baner',
    'Hinjewadi',
    'Magarpatta',
  ],
  'Surat': [
    'Adajan',
    'Vesu',
    'City Light',
    'Athwalines',
    'Varachha',
    'Nanpura',
  ],
  'Jaipur': [
    'Malviya Nagar',
    'Vaishali Nagar',
    'Mansarovar',
    'C-Scheme',
    'Raja Park',
    'Tonk Road',
  ],
  'Lucknow': [
    'Hazratganj',
    'Gomti Nagar',
    'Indira Nagar',
    'Alambagh',
    'Charbagh',
    'Aminabad',
  ],
  'Indore': [
    'Vijay Nagar',
    'Rajwada',
    'Palasia',
    'Bhawarkuan',
    'MR 10 Road',
    'Rau',
  ],
  'Bhopal': [
    'Arera Colony',
    'MP Nagar',
    'Kolar Road',
    'Shahpura',
    'New Market',
    'BHEL Township',
  ],
  'Nagpur': [
    'Dharampeth',
    'Sitabuldi',
    'Civil Lines',
    'Manish Nagar',
    'Pratap Nagar',
    'Sadar',
  ],
  'Vadodara': [
    'Alkapuri',
    'Gotri',
    'Manjalpur',
    'Sayajigunj',
    'Fatehgunj',
    'Akota',
  ],
};

String popularCities = 'Mumbai';

// final dummyResellerLead = ResellerLeadOverview(
//   id: "Lead005",
//   createdBy: "Agent999",
//   updatedBy: "Agent123",
//   name: "Karan Mehta",
//   email: "karan.mehta@example.com",
//   phone: "9988776655",
//   propertyId: "Prop005",
//   resellerId: "Reseller005",
//   source: "broker",
//   status: "lost",
//   stage: "deal_lost",
//   notes: "Client backed out due to high price",
//   lastContactedAt: DateTime.parse("2025-09-19T16:00:00.000Z"),
//   isFake: false,
//   fakeReason: null,
//   markedFakeBy: null,
//   markedFakeAt: null,
//   customFields: Items(
//     id: "prop_001",
//     createdBy: "user_123",
//     updatedBy: "user_456",
//     title: "Luxury 3BHK Apartment in Pune",
//     type: "residential",
//     listingType: "Sale",
//     propertyType: "apartment",
//     propertyDescription:
//         "Spacious 3BHK apartment with modern amenities located in Kalyani Nagar, Pune.",
//     keywords: ["3BHK", "Balcony", "Furnished", "Near IT Park"],
//     propertyImages: [
//       "https://example.com/images/property1.jpg",
//       "https://example.com/images/property2.jpg",
//     ],
//     propertyMedia: PropertyMedia(
//       images: [
//         "https://example.com/media/image1.jpg",
//         "https://example.com/media/image2.jpg",
//       ],
//       videos: ["https://example.com/media/video1.mp4"],
//       documents: ["https://example.com/media/floorplan.pdf"],
//     ),
//     propertyDetails: PropertyDetails(
//       bhk: 3,
//       balcony: 2,
//       bathroom: 3,
//       amenities: ["Gym", "Swimming Pool", "Power Backup", "Parking"],
//       zoneType: "Residential Zone",
//       floorInfo: FloorInfo(floorNumber: 5, totalFloors: 12),
//       furnishInfo: FurnishInfo(
//         furnishType: "Fully Furnished",
//         furnishDetails: FurnishDetails(
//           modularKitchen: true,
//           wardrobes: true,
//           acInstalled: true,
//         ),
//       ),
//       parkingInfo: ParkingInfo(covered: true, open: false),
//       financialInfo: FinancialInfo(
//         price: 12500000,
//         propertyRentPerMonth: 0,
//         maintenance: 2500,
//         pricePerSqft: 8500,
//         brokerCommission: 2,
//         propertySecurityDeposit: 0,
//         negotiable: true,
//       ),
//       possessionInfo: PossessionInfo(
//         possessionStatus: "Ready to Move",
//         propertyAgeInYear: "2",
//       ),
//       propertyFacing: "East",
//       propertyCondition: "Excellent",
//       propertyCarpetArea: 1400.0,
//       propertyBuiltUpArea: 1650.0,
//       propertyCarpetAreaUnit: "sqft",
//       propertyBuiltUpAreaUnit: "sqft",
//       facilitiesInfo: FacilitiesInfo(
//         minSeats: 0,
//         numberOfCabins: 0,
//         numberOfMeetingRooms: 0,
//       ),
//       pgInfo: PgInfo(
//         pgName: "Elite PG",
//         pgFor: "Students",
//         pgSuitedFor: "Boys",
//         pgMealOffered: "Breakfast, Dinner",
//         pgCommonArea: "TV Room, Study Hall",
//         pgManageBy: "Owner",
//         pgOwnerStaysAtPg: false,
//         mealChargesPerMonth: 3000,
//         electricityChargesPerMonth: 1500,
//         pgRules: PgRules(
//           nonVegAllowed: true,
//           smokingAllowed: false,
//           drinkingAllowed: false,
//           petsAllowed: false,
//           lateEntryAllowed: true,
//           lateEntryTime: "11:00 PM",
//           visitorAllowed: true,
//           gurdianAllowed: false,
//         ),
//         pgRoomInfo: [
//           PgRoomInfo(
//             roomType: "Single Sharing",
//             totalBeds: 1,
//             roomFacilityInfo: RoomFacilityInfo(
//               wifi: true,
//               tv: true,
//               ac: true,
//               other: "Private Balcony",
//             ),
//           ),
//           PgRoomInfo(
//             roomType: "Double Sharing",
//             totalBeds: 2,
//             roomFacilityInfo: RoomFacilityInfo(
//               wifi: true,
//               tv: false,
//               ac: true,
//               other: "Common Bathroom",
//             ),
//           ),
//         ],
//       ),
//     ),
//     address: "Sunshine Residency, Kalyani Nagar",
//     city: "Pune",
//     state: "Maharashtra",
//     zipCode: "411014",
//     location: "18.5516, 73.9035",
//     nearbyLocations: [
//       NearbyLocations(name: "Phoenix Mall", distance: 1.5),
//       NearbyLocations(name: "Pune Airport", distance: 4.2),
//     ],
//     reraId: "RERA-PN-12345",
//     propertyStatus: "Available",
//     builderName: "Sunshine Developers",
//     projectName: "Sunshine Residency",
//     ownerPhone: "+91 9876543210",
//     ownerName: "Rahul Mehta",
//     ownerEmail: "rahul.mehta@example.com",
//     isVerified: true,
//     verifiedBy: "admin_user",
//     verifiedAt: "2025-10-05T12:00:00Z",
//     totalInquiries: 12,
//     totalViews: 480,
//     approvalStatus: "approved",
//     approvalComment: "All documents verified",
//     approvedBy: "admin_1",
//     approvedAt: "2025-10-06T09:00:00Z",
//     totalFavorites: 14,
//     totalShares: 5,
//     totalVisits: 60,
//     totalSales: 1,
//     totalCommissions: "50000",
//     assignedTo: "agent_009",
//     assignmentDate: "2025-09-01",
//     assignmentExpiryDate: "2025-12-01",
//     potentialEarnings: "1,20,000",
//     assignmentStatus: "active",
//     performanceScore: "8.5",
//     expiryDate: "2026-09-01",
//     lastRenewalDate: "2025-08-01",
//     renewalCount: 2,
//     isExpired: false,
//     totalReports: 0,
//     isHiddenDueToReports: false,
//     lastReportedAt: null,
//     createdAt: "2025-07-01T10:00:00Z",
//     updatedAt: "2025-09-15T10:00:00Z",
//   ),
//   createdAt: DateTime.parse("2025-09-05T14:00:00.000Z"),
//   updatedAt: DateTime.parse("2025-09-19T16:00:00.000Z"),
// );

// Example: list of dummy leads
List<Map<String, dynamic>> propertyCommissionList = [
  {
    'title': 'Luxury Apartment',
    'address': '123 Main St, City',
    'price': '1,00,000',
    'views': '1.2K',
    'postedAgo': '2d',
    'commission': '5,000',
    'commissionRate': '5',
    'image': 'https://images.pexels.com/photos/323705/pexels-photo-323705.jpeg',
  },
  {
    'title': 'Modern Villa',
    'address': 'Palm Avenue, Mumbai',
    'price': '2,50,000',
    'views': '2.1K',
    'postedAgo': '1d',
    'commission': '12,000',
    'commissionRate': '6',
    'image': 'https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg',
  },
];

final List<double> monthlyData = [
  15,
  28,
  35,
  42,
  18,
  25,
  38,
  45,
  22,
  30,
  12,
  40,
];

final List<String> months = [
  'Jan',
  'Feb',
  'Mar',
  'Apr',
  'May',
  'Jun',
  'Jul',
  'Aug',
  'Sep',
  'Oct',
  'Nov',
  'Dec',
];
